const MIN_USERNAME_LENGTH = 3;
const MAX_USERNAME_LENGTH = 16;

const MIN_PASSWORD_LENGTH = 8;
const MAX_PASSWORD_LENGTH = 20;

const USERS_PAGE_LIMIT = 10;
const LOGS_PAGE_LIMIT = 13;

const MAX_USER_DEVICES = 3;

export {
    MIN_USERNAME_LENGTH,
    MAX_USERNAME_LENGTH,
    MIN_PASSWORD_LENGTH,
    MAX_PASSWORD_LENGTH,
    USERS_PAGE_LIMIT,
    LOGS_PAGE_LIMIT,
    MAX_USER_DEVICES,
};
