const MIN_USERNAME_LENGTH = 3;
const MAX_USERNAME_LENGTH = 16;

const MIN_PASSWORD_LENGTH = 8;
const MAX_PASSWORD_LENGTH = 20;

const DEFAULT_PAGE_LIMIT = 10;

export {
    MIN_USERNAME_LENGTH,
    MAX_USERNAME_LENGTH,
    MIN_PASSWORD_LENGTH,
    MAX_PASSWORD_LENGTH,
    DEFAULT_PAGE_LIMIT,
};
